# Generated by Django 2.2.4 on 2019-11-09 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestME',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 8, 34, 45, 457316))),
                ('descripcion', models.CharField(default='Riesgo Musculo Esqueletico', max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('diagnostico', models.CharField(max_length=30, null=True)),
                ('idRiesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Riesgo')),
                ('usuario', models.ForeignKey(on_delete=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                                          to=settings.AUTH_USER_MODEL),
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SabiasQue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('demostracion', models.ImageField(null=True, upload_to='demostraciones')),
                ('idRiesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='PosibleEnfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('idRiesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='poblacion',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(blank=True, max_length=100, unique=True)),
                ('Riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDemografico',
            fields=[
                ('id0', models.AutoField(primary_key=True, serialize=False)),
                ('cedula0', models.IntegerField()),
                ('nombre0', models.CharField(max_length=30)),
                ('apellido0', models.CharField(max_length=30)),
                ('sexo0', models.BooleanField()),
                ('peso0', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manoDominante0', models.CharField(max_length=10)),
                ('antiguedadCargo0', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividadFisica0', models.CharField(max_length=30)),
                ('horasActividadFisi0', models.IntegerField()),
                ('variaSuJornada0', models.BooleanField()),
                ('cargo0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Cargo')),
                ('dependencia0',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.Dependencia')),
                ('test0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='ManoME',
            fields=[
                ('id4', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia4', models.IntegerField(null=True)),
                ('molestiaSepresenta4', models.IntegerField(null=True)),
                ('laMolestiaEs4', models.IntegerField(null=True)),
                ('seEfectuaMolestia4', models.IntegerField(null=True)),
                ('intensidadMolestia4', models.IntegerField(null=True)),
                ('otraActividadMolestaAu4', models.IntegerField(null=True)),
                ('otraActividadMolestaDis4', models.IntegerField(null=True)),
                ('duracionMolestia4', models.IntegerField(null=True)),
                ('interfirioTrabajo4', models.IntegerField(null=True)),
                ('test4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='HombroME',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia1', models.IntegerField(null=True)),
                ('molestiaSepresenta1', models.IntegerField(null=True)),
                ('laMolestiaEs1', models.IntegerField(null=True)),
                ('seEfectuaMolestia1', models.IntegerField(null=True)),
                ('intensidadMolestia1', models.IntegerField(null=True)),
                ('otraActividadMolestaAu1', models.IntegerField(null=True)),
                ('otraActividadMolestaDis1', models.IntegerField(null=True)),
                ('duracionMolestia1', models.IntegerField(null=True)),
                ('interfirioTrabajo1', models.IntegerField(null=True)),
                ('test1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='EspaldaDorsalME',
            fields=[
                ('id6', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia6', models.IntegerField(null=True)),
                ('molestiaSepresenta6', models.IntegerField(null=True)),
                ('laMolestiaEs6', models.IntegerField(null=True)),
                ('seEfectuaMolestia6', models.IntegerField(null=True)),
                ('intensidadMolestia6', models.IntegerField(null=True)),
                ('otraActividadMolestaAu6', models.IntegerField(null=True)),
                ('otraActividadMolestaDis6', models.IntegerField(null=True)),
                ('duracionMolestia6', models.IntegerField(null=True)),
                ('interfirioTrabajo6', models.IntegerField(null=True)),
                ('test6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='EspaldaBajaME',
            fields=[
                ('id5', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia5', models.IntegerField(null=True)),
                ('molestiaSepresenta5', models.IntegerField(null=True)),
                ('laMolestiaEs5', models.IntegerField(null=True)),
                ('seEfectuaMolestia5', models.IntegerField(null=True)),
                ('intensidadMolestia5', models.IntegerField(null=True)),
                ('otraActividadMolestaAu5', models.IntegerField(null=True)),
                ('otraActividadMolestaDis5', models.IntegerField(null=True)),
                ('duracionMolestia5', models.IntegerField(null=True)),
                ('interfirioTrabajo5', models.IntegerField(null=True)),
                ('test5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='DefinicionEnfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion1', models.CharField(max_length=400)),
                ('imagen', models.ImageField(null=True, upload_to='photo')),
                ('enfermedad',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.PosibleEnfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='CuelloME',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia2', models.IntegerField(null=True)),
                ('molestiaSepresenta2', models.IntegerField(null=True)),
                ('laMolestiaEs2', models.IntegerField(null=True)),
                ('seEfectuaMolestia2', models.IntegerField(null=True)),
                ('intensidadMolestia2', models.IntegerField(null=True)),
                ('otraActividadMolestaAu2', models.IntegerField(null=True)),
                ('otraActividadMolestaDis2', models.IntegerField(null=True)),
                ('duracionMolestia2', models.IntegerField(null=True)),
                ('interfirioTrabajo2', models.IntegerField(null=True)),
                ('test2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
        migrations.CreateModel(
            name='CodoME',
            fields=[
                ('id3', models.AutoField(primary_key=True, serialize=False)),
                ('lugarMolestia3', models.IntegerField(null=True)),
                ('molestiaSepresenta3', models.IntegerField(null=True)),
                ('laMolestiaEs3', models.IntegerField(null=True)),
                ('seEfectuaMolestia3', models.IntegerField(null=True)),
                ('intensidadMolestia3', models.IntegerField(null=True)),
                ('otraActividadMolestaAu3', models.IntegerField(null=True)),
                ('otraActividadMolestaDis3', models.IntegerField(null=True)),
                ('duracionMolestia3', models.IntegerField(null=True)),
                ('interfirioTrabajo3', models.IntegerField(null=True)),
                ('test3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Riesgos.TestME')),
            ],
        ),
    ]
